# TOD-KAT Lite Configuration for Google Colab
# =============================================

# Architecture Selection
architecture_name: "todkat_lite"

# Data Paths (Colab)
data_root: "/content/drive/MyDrive/dlfa_capstone"

# Model Architecture
output_dim: 7
topic_embedding_dim: 100
use_knowledge: false
n_topics: 50
rel_transformer_layers: 2
rel_heads: 4
mlp_hidden_size: 512

# Training Parameters  
batch_size: 8
num_epochs: 25
learning_rate: 1e-4
weight_decay: 1e-4
focal_gamma: 2.0
eta_min: 1e-7

# Data Processing
text_max_len: 128
audio_input_type: "raw_wav"
dataloader_num_workers: 4

# Encoders
text_encoder_model_name: "roberta-base"
audio_encoder_model_name: "facebook/wav2vec2-base-960h"
freeze_text_encoder: true
freeze_audio_encoder: true

# Experiment Settings
experiment_name: "colab_test"
run_name: "todkat_lite"
random_seed: 42

# Training Options
use_mixed_precision: true
grad_accumulation_steps: 1
early_stopping_patience: 5

# Class weights (MELD distribution)
class_weights: [0.8, 1.5, 2.0, 2.5, 1.2, 1.8, 2.2]

# Output Directories
output_dir: "/content/emotion-classifier-capstone/output" 