# TOD-KAT Lite Config - Optimized for 7.5M Parameters
# ===================================================

# CRITICAL: Architecture selection
architecture_name: todkat_lite

# Experiment settings
experiment_name: colab_run_todkat_lite_optimal
random_seed: 42

# Data paths
data_root: /content/drive/MyDrive/dlfa_capstone/meld_data

# Model architecture settings - SIMPLIFIED FOR DEBUGGING  
output_dim: 7
topic_embedding_dim: 64      
n_topics: 64                 
rel_transformer_layers: 2    # REDUCED: for debugging
rel_heads: 4                 # REDUCED: for debugging  
projection_dim: 256          
mlp_hidden_size: 1024        
mlp_dropout_rate: 0.3
use_knowledge: true          
knowledge_dim: 32            

# TOD-KAT Specific Features - DISABLED FOR DEBUGGING
use_topic_mlps: false        # DISABLED: for debugging
use_knowledge_attention: false # DISABLED: for debugging
transformer_dim_feedforward: 512

# Encoder settings
text_encoder_model_name: roberta-base
audio_encoder_model_name: facebook/wav2vec2-base-960h
audio_input_type: raw_wav
freeze_text_encoder: true
freeze_audio_encoder: true

# Training settings
batch_size: 8
num_epochs: 25
learning_rate: 1e-4
weight_decay: 1e-4
optimizer_name: AdamW

# Loss settings
focal_gamma: 2.0

# Class weights for MELD emotion imbalance
class_weights: [1.62, 8.22, 11.19, 1.40, 0.45, 2.69, 2.00]

# Training options
use_mixed_precision: true
early_stopping_patience: 5
grad_accumulation_steps: 1

# DataLoader settings
dataloader_num_workers: 2

# Text processing
text_max_length: 128

# Scheduler settings
eta_min: 1e-7 