# Simple Dialog-RNN Config (No Hydra syntax)
# ============================================

# CRITICAL: Architecture selection
architecture_name: dialog_rnn

# Experiment settings
experiment_name: colab_run_dialog_rnn
random_seed: 42

# Data paths
data_root: /content/drive/MyDrive/dlfa_capstone/meld_data

# Model architecture settings
output_dim: 7
gru_hidden_size: 256
context_window: 10
mlp_hidden_size: 2048

# Encoder settings
text_encoder_model_name: roberta-base
audio_encoder_model_name: facebook/wav2vec2-base-960h
audio_input_type: raw_wav
freeze_text_encoder: false  # Allow fine-tuning
freeze_audio_encoder: false  # Allow fine-tuning

# Training settings
batch_size: 8
num_epochs: 30
learning_rate: 1e-5
weight_decay: 1e-4
optimizer_name: AdamW

# Loss settings
focal_gamma: 2.0

# Class weights for MELD emotion imbalance
class_weights: [1.62, 8.22, 11.19, 1.40, 0.45, 2.69, 2.00]

# Training options
use_mixed_precision: true
early_stopping_patience: 5
grad_accumulation_steps: 1

# DataLoader settings
dataloader_num_workers: 2

# Additional settings retained from Hydra config
mlp_dropout_rate: 0.3 