# Minimal DialogRNN config for debugging - matches expected parameter count
data_root: /content/drive/MyDrive/dlfa_capstone/meld_data
experiment_name: minimal_dialog_rnn_debug
architecture_name: dialog_rnn

# Model settings
output_dim: 7
batch_size: 4
num_epochs: 2
learning_rate: 2e-4
weight_decay: 1e-4

# DialogRNN specific settings  
mlp_hidden_size: 2048
gru_hidden_size: 128
context_window: 0

# NO fine-tuning - keep encoders frozen for 5.3M parameter count
# fine_tune section completely removed

# Simple loss settings
focal_gamma: 2.0
class_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

# Minimal training settings
early_stopping_patience: 5
use_mixed_precision: false
grad_accumulation_steps: 1
random_seed: 42
eta_min: 1e-7 